#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# edit the haproxy config file
haproxy_config=\
"
frontend  devnjeri-frontend
        bind *:80
        mode http
        default_backend devnjeri-backend
backend devnjeri-backend
        balance roundrobin
        server 119970-web-01 100.26.232.40:80 check
        server 119970-web-02 54.162.241.208:80 check
"
echo "$haproxy_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

#restart program after updating settings
sudo service haproxy restart